---
- name: Deploy Static Web Application
  hosts: myserver 
  become: true

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy web application files
      copy:
        src: "{{ playbook_dir }}/../webapp/"
        dest: "/usr/share/nginx/html/"
      notify:
        - Restart Web Server

  handlers:
    - name: Restart Web Server
      systemd:
        name: nginx
        state: restarted

